# © 2021-2023 Marco Bresciani
#
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.
# This file is offered as-is, without any warranty.
#
# SPDX-FileCopyrightText: 2021-2023 Marco Bresciani
# SPDX-License-Identifier: FSFAP

#+TITLE: TKCompanionApp - ADR Template
#+AUTHOR: [[https://codeberg.org/marco.bresciani/][Marco Bresciani]]
#+LANGUAGE:  en
#+DATE: 2023-08-14
#+OPTIONS: toc:nil
#+TODO: PROPOSED(p) | ACCEPTED(a) DEPRECATED(d)

* PROPOSED [short title of solved problem and solution]
:PROPERTIES:
:CUSTOM_ID: short-title-of-solved-problem-and-solution
:END:

These documents have names that are short noun phrases.
For example, "=ADR 1: Deployment on Ruby on Rails 3.0.10=" or
"=ADR 9: LDAP for Multitenant Integration="

** Context
:PROPERTIES:
:CUSTOM_ID: context
:END:

This section describes the forces at play, including technological,
political, social, and project local.
These forces are probably in tension, and should be called out as such.
The language in this section is value-neutral.
It is simply describing facts.

** Decision
:PROPERTIES:
:CUSTOM_ID: decision
:END:

This section describes our response to these forces.
It is stated in full sentences, with active voice. "=We will ...=".

** Status
:PROPERTIES:
:CUSTOM_ID: status
:END:

A decision may be "=proposed=" if the project stakeholders haven't
agreed with it yet, or "=accepted=" once it is agreed.
If a later ADR changes or reverses a decision, it may be marked as
"=deprecated=" or "=superseded=" with a reference to its replacement.

** Consequences
:PROPERTIES:
:CUSTOM_ID: consequences
:END:

This section describes the resulting context, after applying the
decision.
All consequences should be listed here, not just the "positive" ones.
A particular decision may have positive, negative, and neutral
consequences, but all of them affect the team and project in the future.
