# © 2021-2024 Marco Bresciani
# 
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.
# This file is offered as-is, without any warranty.
# 
# SPDX-FileCopyrightText: 2021-2024 Marco Bresciani
# SPDX-License-Identifier: FSFAP

#+AUTHOR: Marco Bresciani
#+LANGUAGE:  en
#+OPTIONS: toc:nil
#+TITLE: TKCompanionApp - 9 Encrypted Storage
#+TODO: PROPOSED(p) | ACCEPTED(a) DEPRECATED(d)
# -*- mode: org; coding: utf-8-dos; -*-

* DEPRECATED 9 Encrypted Storage

 See [[file:012-async-storage.org][12 Async Storage]].

** Context

Giving the possibility to change settings of the application, it is
better for the user to be able to keep those settings valid through all
the uses of the application, even if the application is frozen or
terminated.

** Decision

The app is going to use the
[[https://github.com/emeraldsanto/react-native-encrypted-storage][React
Native Encrypted Storage]] that is based on
[[https://react-native-async-storage.github.io/async-storage/][React
Native Async Storage]], but in encrypted form, for better security.
There is no need to use files for this purpose.

** Status

+Accepted.+
Deprecated on 2022-05-19.

** Consequences

There will be soon the need to use a password of the phone unlock
mechanism to protect those encrypted data.
