# © 2021-2023 Marco Bresciani
# 
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.
# This file is offered as-is, without any warranty.
# 
# SPDX-FileCopyrightText: 2021-2023 Marco Bresciani
# SPDX-License-Identifier: FSFAP

#+AUTHOR: [[https://codeberg.org/marco.bresciani/][Marco Bresciani]]
#+LANGUAGE:  en
#+OPTIONS: toc:nil
#+TITLE: TKCompanionApp - 15 Use Org Changelog
#+TODO: PROPOSED(p) | ACCEPTED(a) DEPRECATED(d)
# -*- mode: org; coding: utf-8-dos; -*-

* ACCEPTED 15 Use Org Changelog

Deprecates [[file:004-keep-a-changelog.org][4 Keep A Changelog]].

** Context

*What is a changelog?*
A changelog is a file which contains a curated, chronologically ordered
list of notable changes for each version of a project.

*Why keep a changelog?*
To make it easier for users and contributors to see precisely what
notable changes have been made between each release (or version) of the
project.

*Who needs a changelog?*
People do.
Whether consumers or developers, the end users of software are human
beings who care about what's in the software.
When the software changes, people want to know why and how.

** Decision

The project will use and keep a =CHANGELOG.org= file, in Org markup
format, /based on/ guidelines and rules of
[[https://keepachangelog.com/en/1.1.0/][keep a changelog 1.1.0]].

** Status

Accepted.

** Consequences

The =CHANGELOG.md= file shall be taken care of and kept updated.
